### ISSUE TITLE
Add features button gets stuck out of place

### ISSUE THREAD

**Issue by coreywoodfield** [byu-oit/android-byu-suite-v2#375]
If you remove a favorite, the snackbar pops up. If you open another feature with just the right timing (It took me about ten tries to recreate it, after I encountered it on accident), the add features button will be stuck in the incorrect position. I think this is a bug with android and not with our app, but I figured I'd log it anyways

![device-2017-04-03-135237](https://cloud.githubusercontent.com/assets/17733030/24629105/1b396cf0-1875-11e7-83c1-c7caf8d44364.png)

**Comment by coreywoodfield** [comment]
I found a way to consistently recreate the bug, but I haven't found a way to fix it. lol

**Comment by romrell4** [comment]
This bug still occurs on some phones. 
- Android 7. LGG 5 (keeps going up)
- Android 7. Samsung S7 (goes up once)
See me for examples
