### ISSUE TITLE
Bug in learning suite

### ISSUE THREAD

**Issue by coreywoodfield** [byu-oit/android-byu-suite-v2#518]
![screenshot_20180316-133231](https://user-images.githubusercontent.com/17733030/37541204-4d77f36a-291f-11e8-8952-89d9a3a9a772.png)
Note the double drop-down arrows in the top right. One worked as expected, the other didn't do anything.

Steps to reproduce:
I opened the BYU app (I hadn't used it in a while) and I was already deep inside the learning suite feature. I hit back a couple times to get to the main learning suite activity, and a progress dialog popped up, as it needed to load my classes again. I hit the back button before it finished, and the screen ended up like you see in the screenshot. It'll probably be easier to reproduce if you go to developer options and turn on the "Don't keep activities" option.

I'm on Android 8.1.0

**Comment by romrell4** [comment]
Assigning to @geogor37

**Comment by romrell4** [comment]
@coreywoodfield Are you able to reproduce the error? Or did is seem to only happen this once?

**Comment by coreywoodfield** [comment]
If I have on the "don't keep activities" option I can reproduce it every time
![screenshot_20180316-135446](https://user-images.githubusercontent.com/17733030/37541844-b660046a-2921-11e8-869d-599b52762134.png)

**Comment by coreywoodfield** [comment]
It looks like every time it loads the semesters it adds a new spinner to the toolbar

**Comment by coreywoodfield** [comment]
Other features with spinners (e.g. testing center) don't have this problem. It seems like learning suite is adding a new spinner every time it loads the semesters

**Comment by romrell4** [comment]
@coreywoodfield Are you able to reproduce this error without the developer setting active?

**Comment by coreywoodfield** [comment]
The first time I got it it was without the setting active but you have to
wait for Android to run out of memory and get rid of the activity, so it
would take a while

**Comment by romrell4** [comment]
@coreywoodfield The fix has been added and has been staged for deploy. Look forward to the fix in the next release.
